### ISSUE TITLE
Error Logging In

### ISSUE THREAD

**Issue by itsgabraf** [e-mcgee/paradox_platform#25]
Confused, why does it say "Connected to Alarm!" but then tells me I can't log in? Am I doing something wrong here? Also, under password, do I put the password to the IP device (IP150) or one of my users panel code?

[2018-6-15 08:54:56] [Paradox] Initializing Paradox platform...
[2018-6-15 08:54:56] [Paradox] Platform initialisation
[2018-6-15 08:54:56] [Paradox] Looking for accessories in config file
[2018-6-15 08:54:56] [Paradox] Accessory
[2018-6-15 08:54:56] [Paradox] Alarm_Partition_1
[2018-6-15 08:54:56] [Paradox] Found: Alarm_Partition_1 [Alarm]
[2018-6-15 08:54:56] [Paradox] Initial Alarm State: 
[2018-6-15 08:54:56] [Paradox] { status: 'Disarmed' }
[2018-6-15 08:54:56] [Paradox] Setting alarm state to 3
[2018-6-15 08:54:56] [Paradox] Accessory
[2018-6-15 08:54:56] [Paradox] inactive
[2018-6-15 08:54:56] [Paradox] Found: inactive [Alarm]
[2018-6-15 08:54:56] [Paradox] Accessory
[2018-6-15 08:54:56] [Paradox] Connected
[2018-6-15 08:54:56] [Paradox] Found: Connected [Connected]
[2018-6-15 08:54:56] [Paradox] Initialy connected to alarm
[2018-6-15 08:54:56] [Paradox] Accessory
[2018-6-15 08:54:56] [Paradox] Garage
[2018-6-15 08:54:56] [Paradox] Found: Garage [Motion Sensor]
[2018-6-15 08:54:56] [Paradox] Debounce delay:
[2018-6-15 08:54:56] [Paradox] 500
[2018-6-15 08:54:56] [Paradox] Accessory
[2018-6-15 08:54:56] [Paradox] Front Door Reed
[2018-6-15 08:54:56] [Paradox] Found: Front Door Reed [Contact Sensor]
[2018-6-15 08:54:56] [Paradox] Debounce delay:
[2018-6-15 08:54:56] [Paradox] 0
[2018-6-15 08:54:56] [Paradox] Accessory
[2018-6-15 08:54:56] [Paradox] Entry
[2018-6-15 08:54:56] [Paradox] Found: Entry [Motion Sensor]
[2018-6-15 08:54:56] [Paradox] Debounce delay:
[2018-6-15 08:54:56] [Paradox] 500
[2018-6-15 08:54:56] [Paradox] Accessory
[2018-6-15 08:54:56] [Paradox] Back Door Reed
[2018-6-15 08:54:56] [Paradox] Found: Back Door Reed [Contact Sensor]
[2018-6-15 08:54:56] [Paradox] Debounce delay:
[2018-6-15 08:54:56] [Paradox] 0
[2018-6-15 08:54:56] [Paradox] Accessory
[2018-6-15 08:54:56] [Paradox] Living Room
[2018-6-15 08:54:56] [Paradox] Found: Living Room [Motion Sensor]
[2018-6-15 08:54:56] [Paradox] Debounce delay:
[2018-6-15 08:54:56] [Paradox] 500
[2018-6-15 08:54:56] [Paradox] Accessory
[2018-6-15 08:54:56] [Paradox] Upstairs Landing
[2018-6-15 08:54:56] [Paradox] Found: Upstairs Landing [Motion Sensor]
[2018-6-15 08:54:56] [Paradox] Debounce delay:
[2018-6-15 08:54:56] [Paradox] 500
[2018-6-15 08:54:56] [Paradox] Initializing platform accessory 'Alarm_Partition_1'...
[2018-6-15 08:54:56] [Paradox] Initializing platform accessory 'Connected'...
[2018-6-15 08:54:56] [Paradox] Initializing platform accessory 'Garage'...
[2018-6-15 08:54:56] [Paradox] Initializing platform accessory 'Front Door Reed'...
[2018-6-15 08:54:56] [Paradox] Initializing platform accessory 'Entry'...
[2018-6-15 08:54:56] [Paradox] Initializing platform accessory 'Back Door Reed'...
[2018-6-15 08:54:56] [Paradox] Initializing platform accessory 'Living Room'...
[2018-6-15 08:54:56] [Paradox] Initializing platform accessory 'Upstairs Landing'...
[2018-6-15 08:54:57] [Paradox] Cannot get status - not logged in
[2018-6-15 08:54:57] [Paradox] Cannot set Alarm - not logged in
[2018-6-15 08:55:02] [Paradox] Mute : [false]
[2018-6-15 08:55:02] [Paradox] Logging in
[2018-6-15 08:55:02] [Paradox] Getting Status - Connected to alarm!
[2018-6-15 08:55:02] [Paradox] Error logging in
[2018-6-15 08:55:07] [Paradox] Mute : [false]
[2018-6-15 08:55:12] [Paradox] Mute : [false]
[2018-6-15 08:55:17] [Paradox] Mute : [false]
[2018-6-15 08:55:22] [Paradox] Mute : [false]
[2018-6-15 08:55:27] [Paradox] Mute : [false]
[2018-6-15 08:55:32] [Paradox] Mute : [false]
[2018-6-15 08:55:37] [Paradox] Mute : [false]
[2018-6-15 08:55:42] [Paradox] Mute : [false]
[2018-6-15 08:55:47] [Paradox] Mute : [false]
[2018-6-15 08:55:52] [Paradox] Mute : [false]
[2018-6-15 08:55:57] [Paradox] Mute : [false]
[2018-6-15 08:56:02] [Paradox] Mute : [false]
[2018-6-15 08:56:07] [Paradox] Mute : [false]
[2018-6-15 08:56:12] [Paradox] Mute : [false]
[2018-6-15 08:56:17] [Paradox] Mute : [false]
[2018-6-15 08:56:22] [Paradox] Mute : [false]
[2018-6-15 08:56:27] [Paradox] Mute : [false]
[2018-6-15 08:56:32] [Paradox] Mute : [false]
[2018-6-15 08:56:37] [Paradox] Mute : [false]

**Comment by ethan4** [comment]
I'm also stuck at this point. Perhaps this plugin is based on an older version of the IP module, here's what i've got.

Key | Value
-- | --
Panel |
Type | SP4000
Firmware version | 5.20
-- | --
IP Module |
Serial number | XX XX XX XX
Firmware version | 1.39.02
Hardware | 020
ECO | N009
Serial boot | N/A
IP boot | 2.12
Serial number | XX XX XX XX

**Comment by e-mcgee** [comment]
It seems to fail on login.  You need the IP module password.  Check your IP address, port and password.  Should work on IP150.  Other have it working on that.

**Comment by urosbe** [comment]
I have setup Homebridge for my accessories at home and Paradox with IP150 is one of them that I would really like to be able to control with HomeKit. Currently I have motions sensors, door and window contacts installed. The problem is the same as other users explained in this issue. I am not able to login in. I have double checked IP, port and module password and I am able to login to IP150's web admin interface with those credentials (I have to enter user PIN also, not only module password), but not with this plugin. It keeps saying "Error logging in". Is maybe a problem that I do not have MQTT installed and I have set this parameter to false?

Here is my config (I have replaced real values with X for security reason):
```
            "platform": "Paradox",
            "ip": "192.168.1.X",
            "port": X,
            "password": "X",
            "mqtt": false,
            "mqtturl": "x.x.x.x",
            "qos": 0,
            "retain": false,
            "mqttusername": "user",
            "mqttpassword": "password", 
            "logindelay": 3800,
            "polldelay": 5000,
            "waitafterlogin": 600,
            "delaybetweencmds": 250,
            "logoutdelay": 500,
            "logindelayafterreconnect": 1000,
            "accessories": [...]
```

Here is my hardware list:
PANEL:
Type | EVO192
Firmware version | 4.50

IP MODULE (IP150):
Firmware version | 1.39.02
Hardware | 020
ECO | N009
Serial boot | N/A
IP boot | 2.12

Any advice how to solve logging problem is appreciated!

**Comment by e-mcgee** [comment]
Hi. I suggest you play around with the delay parameters ro see if you can fix the problem. Try making them longer. I tuned these to be optimal for my setup but may be different in your setup. These are in milliseconds.

**Comment by e-mcgee** [comment]
I have published a new version.  The issue you experienced is that the Connected flag gets set to false on a failed login which means that it stops attempting to log in. I fixed this behaviour so it should try to log in again.  I have not yet been able to test this on my own setup and will try so as soon as I have time.  You can test on your setup and let me know.

**Comment by urosbe** [comment]
Hi! I have just upgraded plugin with latest version, but unfortunatelly problem is still there. Once I start homebridge, I get the following status:
```
[Paradox] Cannot get status - not logged in
[Paradox] Cannot set Alarm - not logged in
```

I have even tried to change port to completely different one (from default 10000), but error message is the same. I have double checked IP in port number, because if I try to log in to web interface of IP module with http://IP:PORT I can login without a problem. But it is true that IP module requires to enter two codes - PIN code and Module password code, but there is only one password parameter in config.json available for Paradox Homebridge plugin.

**Comment by e-mcgee** [comment]
Hi,

can you confirm that you still experience the following log output as per the previous sample by @itsgabraf ? :
[2018-6-15 08:54:57] [Paradox] Cannot get status - not logged in
[2018-6-15 08:54:57] [Paradox] Cannot set Alarm - not logged in
[2018-6-15 08:55:02] [Paradox] Mute : [false]
[2018-6-15 08:55:02] [Paradox] Logging in
[2018-6-15 08:55:02] [Paradox] Getting Status - Connected to alarm!
[2018-6-15 08:55:02] [Paradox] Error logging in
[2018-6-15 08:55:07] [Paradox] Mute : [false]
[2018-6-15 08:55:12] [Paradox] Mute : [false]
[2018-6-15 08:55:17] [Paradox] Mute : [false]
[2018-6-15 08:55:22] [Paradox] Mute : [false]
[2018-6-15 08:55:27] [Paradox] Mute : [false]
[2018-6-15 08:55:32] [Paradox] Mute : [false]
[2018-6-15 08:55:37] [Paradox] Mute : [false]
[2018-6-15 08:55:42] [Paradox] Mute : [false]
[2018-6-15 08:55:47] [Paradox] Mute : [false]
[

The fix I did was to continue to try to log in even after failed attempts.  Before it would set the Connected flag to false which stopped the login attempts.  I now removed this setting so the code will continue to  try to log in.  I tested on a Raspberry Pi which gave me the login error and after the second login attempt it was able to log into the alarm.  The initial login still fails but it gets to log in successfully thereafter.

The login to the IP module only needs the module password.  I use IP100 but other users use IP150 and it works fine.

**Comment by urosbe** [comment]
Here is my latest log:

pi@raspberrypi:~ $ homebridge
[2019-2-11 08:15:08] Loaded config.json with 1 platform.
[2019-2-11 08:15:08] ---
[2019-2-11 08:15:11] Loaded plugin: homebridge-paradox-securitysystem
[2019-2-11 08:15:11] Registering platform 'homebridge-paradox.Paradox'
[2019-2-11 08:15:11] ---
[2019-2-11 08:15:11] Loading 1 platform...
[2019-2-11 08:15:11] [Paradox] Initializing Paradox platform...
[2019-2-11 08:15:11] [Paradox] Platform initialisation
[2019-2-11 08:15:11] [Paradox] Looking for accessories in config file
[2019-2-11 08:15:11] [Paradox] Accessory
[2019-2-11 08:15:11] [Paradox] Alarm_Partition_1
[2019-2-11 08:15:11] [Paradox] Found: Alarm_Partition_1 [Alarm]
[2019-2-11 08:15:11] [Paradox] Initial Alarm State:
[2019-2-11 08:15:11] [Paradox] { status: 'Disarmed' }
[2019-2-11 08:15:11] [Paradox] Setting alarm state to 3
[2019-2-11 08:15:11] [Paradox] Accessory
[2019-2-11 08:15:11] [Paradox] Alarm_Partition_2|inactive
[2019-2-11 08:15:11] [Paradox] Found: Alarm_Partition_2|inactive [Alarm]
[2019-2-11 08:15:11] [Paradox] Initial Alarm State:
[2019-2-11 08:15:11] [Paradox] { status: 'Disarmed' }
[2019-2-11 08:15:11] [Paradox] Setting alarm state to 3
[2019-2-11 08:15:11] [Paradox] Accessory
[2019-2-11 08:15:11] [Paradox] Connected
[2019-2-11 08:15:11] [Paradox] Found: Connected [Connected]
[2019-2-11 08:15:11] [Paradox] Initialy connected to alarm
[2019-2-11 08:15:11] [Paradox] Accessory
[2019-2-11 08:15:11] [Paradox] Hodnik-vhod
[2019-2-11 08:15:11] [Paradox] Found: Hodnik-vhod [Motion Sensor]
[2019-2-11 08:15:11] [Paradox] Debounce delay:
[2019-2-11 08:15:11] [Paradox] 0
[2019-2-11 08:15:11] [Paradox] Accessory
[2019-2-11 08:15:11] [Paradox] Vhodna vrata
[2019-2-11 08:15:11] [Paradox] Found: Vhodna vrata [Contact Sensor]
[2019-2-11 08:15:11] [Paradox] Debounce delay:
[2019-2-11 08:15:11] [Paradox] 0
[2019-2-11 08:15:11] [Paradox] Initializing platform accessory 'Alarm_Partition_1'...
[2019-2-11 08:15:11] [Paradox] Initializing platform accessory 'Alarm_Partition_2|inactive'...
[2019-2-11 08:15:11] [Paradox] Initializing platform accessory 'Connected'...
[2019-2-11 08:15:11] [Paradox] Initializing platform accessory 'Hodnik-vhod'...
[2019-2-11 08:15:11] [Paradox] Initializing platform accessory 'Vhodna vrata'...
[2019-2-11 08:15:11] [Paradox] Cannot get status - not logged in
[2019-2-11 08:15:11] [Paradox] Cannot get status - not logged in
[2019-2-11 08:15:12] [Paradox] Cannot set Alarm - not logged in
[2019-2-11 08:15:12] [Paradox] Cannot set Alarm - not logged in
[2019-2-11 08:15:13] Homebridge is running on port 51826.
[2019-2-11 08:15:16] [Paradox] Mute : [false][2019-2-11 08:15:16] [Paradox] Mute : [false]
[2019-2-11 08:15:16] [Paradox] Logging in
[2019-2-11 08:15:16] [Paradox] Getting Status - Connected to alarm!
[2019-2-11 08:15:17] [Paradox] Error logging in
[2019-2-11 08:15:21] [Paradox] Mute : [false][2019-2-11 08:15:21] [Paradox] Mute : [false]
[2019-2-11 08:15:21] [Paradox] Logging in
[2019-2-11 08:15:21] [Paradox] Getting Status - Connected to alarm!
[2019-2-11 08:15:22] [Paradox] Error logging in[2019-2-11 08:15:22] [Paradox] Error logging in

I currently have only one door contact sensor "Vhodna vrata" and one motion sensor "Hodnik-vhod" in parameters, later if I manage to get plugin working, I will add other components too.

**Comment by e-mcgee** [comment]
Hi,

It seems as if your logins fail continuously from the logs.  I did some digging and you may have an issue with the firmware version on the IP150.  See: 
https://github.com/Tertiush/ParadoxIP150v2/issues/22

In the post they describe way to downgrade firmware and then block auto update on the IP150.  It seems to be an issue with the IP150.

I still use the old IP100 without any issues.

**Comment by urosbe** [comment]
I have checked and it looks like my IP150 does not have latest firmware: 1.39.02.
Users that were searching for downgrade option all has firmware >=4.0 and they try to downgrade to 1.32, but I already have 1.3x version. My module is 2 years old.

**Comment by github9984** [comment]
@e-mcgee - I am also getting unable to login, running firmware 4.40.
It throws the following exception...
message received
message length =
43
checksum not ok
error logging in

any help will be greatly appreciated.

**Comment by urosbe** [comment]
Since I was not able to connect my Paradox alarm to Homebridge a year ago, I was searching if there are any updates to this plugin. At the same time I have found firmware update for my IP150 module and I have upgraded firmware from 1.39.02 to 3.01.000. The latest is >4.x, but since this version is not supported by the plugin, I have tried 3.x instead. After firmware upgrade I am able to connect to my Paradox system, but arming/disarming and getting the right info from sensors is not working yet. 

When I start Homebridge, I get "Connected" accessory with status "On" in Home on my iPhone and since Homebridge is connected to Paradox, at that time I am unable to connect to panel web interface with url on http://192.168.x.x:10001. As soon as I switch accessorry to "Off" I can connect to web interface, so it looks like Homebridge connection is successfully.

But the problem is, that I don't get right info from sensors and I arming status is not correct.

I have two areas in my Paradox - office and home, so I assume that means 2 partitions:
![areas](https://user-images.githubusercontent.com/7140012/74226010-0cc4ad00-4cbc-11ea-99b9-1fbe1d8ff0dd.png)

Is my config file ok:
```
			{
			"name": "House Doors contact",
			"config": {
				"type": "Contact Sensor",
				"zone": 9,
				"topic": "Paradox/contactsensor1/",
				"debounceDelay" : 0
				}
			},
			{
			"name": "House Motion sens 3",
			"config": {
				"type": "Contact Sensor",
				"zone": 1,
				"topic": "Paradox/contactsensor1/",
				"debounceDelay" : 0
				}
			},
			{
			"name": "Office Doors contact",
			"config": {
				"type": "Contact Sensor",
				"zone": 8,
				"partition": 2,
				"topic": "Paradox/contactsensor1/",
				"debounceDelay" : 0
				}
			},
```
Log:
```
[2/11/2020, 10:51:06 AM] [Paradox] Mute : [false]
[2/11/2020, 10:51:06 AM] [Paradox] Geting Status...
[2/11/2020, 10:51:06 AM] [Paradox] Got status
[2/11/2020, 10:51:06 AM] [Paradox] Results:
[2/11/2020, 10:51:06 AM] [Paradox] Zone 1 off (House Motion sens 3)
[2/11/2020, 10:51:06 AM] [Paradox] Zone 8 off (Office Doors contact)
[2/11/2020, 10:51:06 AM] [Paradox] Zone 9 off (House Doors contact)
[2/11/2020, 10:51:06 AM] [Paradox] Alarmstatus :Disarmed
[2/11/2020, 10:51:06 AM] [Paradox] Alarmstatus :Disarmed
[2/11/2020, 10:51:06 AM] [Paradox] Statusses:
[2/11/2020, 10:51:06 AM] [Paradox] Area 1 - [object Object]
[2/11/2020, 10:51:06 AM] [Paradox] Area 2 - [object Object]
```

Alarmstatus keeps saying Disarmed, even if I arm it and also Zones are off all the time, even if I open the door or trigger motion sensor.
Any idea what I am doing wrong?

**Comment by morphix9** [comment]
Any news on the issues with IP150 with the latest firmware?
@urosbe could you get it up and running? I also have IP150, with the latest firmware, but I'm afraid it won't work.

**Comment by urosbe** [comment]
Unfortunatelly not. I am waiting if maybe author of this plugin will have any idea. I have updated firmware of my IP150 with latest version of 3.x (3.01.000), because I have read that 4.x is not supported and will never be.

**Comment by morphix9** [comment]
A shame :( I have upgraded IP150 a while ago because it wasn't reliable together with Insite Gold (their Mobile app integration). Have you probably tried the other plugin which works on MQTT (https://github.com/Tertiush/ParadoxIP150)? It looks older/outdated but was developed for IP150.

**Comment by morphix9** [comment]
And this one looks even more promising: 
https://github.com/ParadoxAlarmInterface/pai together with https://github.com/arachnetech/homebridge-mqttthing

**Comment by cosmindnl** [comment]
Same issue here, latest firmware on ip150. 

[Homebridge] [4/13/2020, 6:13:47 AM] [Paradox] Checksum not OK
[Homebridge] [4/13/2020, 6:13:47 AM] [Paradox] Error logging in
[Homebridge] [4/13/2020, 6:13:52 AM] [Paradox] Mute : [false]
[Homebridge] [4/13/2020, 6:13:52 AM] [Paradox] Logging in
[Homebridge] [4/13/2020, 6:13:52 AM] [Paradox] Getting Status - Connected to alarm!
[Homebridge] [4/13/2020, 6:13:52 AM] [Paradox] Message received
[Homebridge] [4/13/2020, 6:13:52 AM] [Paradox] message length = 
[Homebridge] [4/13/2020, 6:13:52 AM] [Paradox] 43

**Comment by danieljakab** [comment]
@e-mcgee Hi, I have the same issue as @cosmindnl 
Do you have any thoughts about login with the latest ip150 firmware and your plugin? Are you still developing this plugin, or with newer firmware we should look somewhere else? Thank you for your answer! D

**Comment by erwinloh** [comment]
Hi @e-mcgee - I have exactly the same issue.

Using the master user code to try to login, which works via the web interface.

Panel
Type SP5500
Firmware version 6.91

IP150 module
Firmware version 4.42.02 
Hardware 020
ECO S079
Serial boot N/A
IP boot 2.14

The error I am getting:

13/01/2021, 8:27:34 pm [Paradox] Mute : [false]
13/01/2021, 8:27:34 pm [Paradox] Logging in
13/01/2021, 8:27:34 pm [Paradox] Getting Status - Connected to alarm!
13/01/2021, 8:27:34 pm [Paradox] Message received
13/01/2021, 8:27:34 pm [Paradox] message length = 
13/01/2021, 8:27:34 pm [Paradox] 43
13/01/2021, 8:27:34 pm [Paradox] Checksum not OK
13/01/2021, 8:27:35 pm [Paradox] Error logging in
13/01/2021, 8:27:39 pm [Paradox] Mute : [false]
13/01/2021, 8:27:39 pm [Paradox] Logging in
13/01/2021, 8:27:39 pm [Paradox] Getting Status - Connected to alarm!
13/01/2021, 8:27:39 pm [Paradox] Message received
13/01/2021, 8:27:39 pm [Paradox] message length = 
13/01/2021, 8:27:39 pm [Paradox] 43
13/01/2021, 8:27:39 pm [Paradox] Checksum not OK
13/01/2021, 8:27:40 pm [Paradox] Error logging in
13/01/2021, 8:27:44 pm [Paradox] Mute : [false]
13/01/2021, 8:27:44 pm [Paradox] Logging in
13/01/2021, 8:27:44 pm [Paradox] Getting Status - Connected to alarm!
13/01/2021, 8:27:44 pm [Paradox] Message received
13/01/2021, 8:27:44 pm [Paradox] message length = 
13/01/2021, 8:27:44 pm [Paradox] 43
13/01/2021, 8:27:44 pm [Paradox] Checksum not OK
13/01/2021, 8:27:45 pm [Paradox] Error logging in
13/01/2021, 8:27:49 pm [Paradox] Mute : [false]

**Comment by roscoe24** [comment]
I’m also facing issues with new version of IP150 module, any update?

**Comment by morphix9** [comment]
> I’m also facing issues with new version of IP150 module, any update?

Give [PAI](https://github.com/ParadoxAlarmInterface/pai) a try. Works like a charm together with HomeAssistant.

**Comment by erwinloh** [comment]
Agree - I am using PAI with my HomeKit/ Hoobs setup now, and it works like a charm. Make sure you disable automatic firmware updates.

**Comment by roscoe24** [comment]
> Agree - I am using PAI with my HomeKit/ Hoobs setup now, and it works like a charm. Make sure you disable automatic firmware updates.

I’m battling to get the pai.conf file updated correct, I put in IP details but it checks the serial connection
